S00J1NK1M/lingoda_copycat

app/models/course.rb
db/migrate/20230926101048_create_courses.rb
db/migrate/20230926101416_add_start_at_to_courses.rb
db/migrate/20230926101515_add_end_at_to_courses.rb
db/schema.rb
test/models/course_test.rb

created course model

---

Gemfile
Gemfile.lock
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20230926102858_devise_create_users.rb
db/migrate/20230926103104_add_nickname_to_users.rb
db/schema.rb
test/models/user_test.rb

created user model

---

app/models/teacher.rb
db/migrate/20230926103444_create_teachers.rb
db/schema.rb
test/models/teacher_test.rb

created teacher model

---

app/models/langauge.rb
db/migrate/20230926103813_create_langauges.rb
db/schema.rb
test/models/langauge_test.rb

created language model

---

db/migrate/20230926104742_add_teacher_ref_to_courses.rb
db/migrate/20230926105207_rename_langauges_to_languages.rb
db/migrate/20230926105541_add_language_ref_to_courses.rb
db/schema.rb

I added refences columns to course model

added references to course model

---

app/models/course.rb
app/models/langauge.rb
app/models/teacher.rb
app/models/user.rb

actually it's about associations in models, we are doing validations later

associations added to models

---

config/routes.rb

added route for course controller

---

db/seeds.rb

created fake seed

---

app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
test/controllers/users_controller_test.rb

created users controller

---

app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
config/routes.rb

edited route for courses and bookings controller

edited route for courses and bookings controller

---

app/controllers/pages_controller.rb

edited pages controller

---

db/seeds.rb

created seed again with language&teacher ids

created seed again

---

db/seeds.rb

edited seed with time data

---

app/assets/stylesheets/components/_home.scss
app/views/pages/home.html.erb

changed course time to print

---

app/views/courses/index.html.erb

edited courses index page

---

Gemfile.lock
app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb
app/views/courses/show.html.erb

finished booking controller

---

app/controllers/bookings_controller.rb

changed destroy path

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/bookings/index.html.erb

changed bookings page (removed logout button and added calendar)

changed bookings page

---

app/assets/stylesheets/components/_filters.scss
app/views/shared/_navbar.html.erb

changed login button

---

app/controllers/pages_controller.rb

working on filter

---

app/views/courses/index.html.erb

nickname higlight done

---

app/assets/stylesheets/components/_home.scss
app/views/courses/show.html.erb

changed the size
